### ISSUE TITLE
[Install cmd tool] command not found error

### ISSUE THREAD

**Issue by hanynady** [informatikr/aeson-pretty#15]
I have cabal version 1.22.6.0 and I installed aeson-pretty-0.7.2
when I write : 
=======================
=>cabal install aeson-pretty         
Resolving dependencies...
All the requested packages are already installed:
aeson-pretty-0.7.2
Use --reinstall if you want to reinstall anyway.
=====================
but when I run  aeson-pretty I get zsh: command not found: aeson-pretty

I tried to follow the instructions for installation but I couldn't run it anyway from the terminal 

My OSX version: 10.11.4

**Comment by informatikr** [comment]
Please check the following:

1. Find out where cabal puts executables on your system. Probably ~/.cabal/bin or ~/Library/Haskell/bin. Check if aeson-pretty is installed there: e.g. `ls ~/.cabal/bin`.
2. If yes, does your terminal know the path to the executable? `echo $PATH`

Hope that helps.

**Comment by hanynady** [comment]
Great, it is working right now,
Thank you very much
