### ISSUE TITLE
Doesn't build with `unordered-containers` < 0.2.14.0

### ISSUE THREAD

**Issue by vaibhavsagar** [informatikr/aeson-pretty#41]
[This line](https://github.com/informatikr/aeson-pretty/blob/893fc5166bfaef680740abc27767769dbaad6549/Data/Aeson/Encode/Pretty.hs#L65) uses `mapKeys` which has only existed since `unordered-containers-0.2.14.0`. Can you update the version bounds (and ideally those of the most recently released Hackage version) to reflect this?

**Comment by martijnbastiaan** [comment]
Done, thanks for the report!

**Comment by vaibhavsagar** [comment]
Thanks!
