### ISSUE TITLE
Encode minified with sorted keys

### ISSUE THREAD

**Issue by chrismwendt** [informatikr/aeson-pretty#9]
It would be nice to be able to encode JSON with sorted keys, but still minified without newlines or indentation.

**Comment by mietek** [comment]
I would like the ability to encode JSON with sorted keys, but without newlines, indentation, or any extra spaces.

Even if the JSON is not intended for human readers, it is still nice to have a consistent key ordering for development and debugging purposes.

**Comment by informatikr** [comment]
If your JSON is for human readers (development and debugging) why do you want to remove whitespace?

The way I use aeson-pretty, and presumably most people, is to have a flag select the encoding. For example a query param "debug" for a webservice, or a command line argument "-h/--human-readable" or similar.

**Comment by seagreen** [comment]
> The problem I see is that whitespace, newlines and sorted keys are not the only issue in JSON canonicalization. At least number and string representation need to be canonical. And maybe more ... I think this is a very hairy problem, and it's easy not to consider many of the potential pitfalls. That's why I am trying to avoid it so much.

I know it's a tough problem, but would you be interested in expanding the scope of aeson-pretty to include these kind of canonicalization issues? Unfortunately I'm stuck needing a JSON canonicalization library in haskell:-) If you want to keep aeson-pretty purely for making nice human readable JSON that's fine too, I think it's smart to stick with original goals sometimes.

**Comment by mietek** [comment]
> If your JSON is for human readers (development and debugging) why do you want to remove whitespace?

Because sometimes removing whitespace actually aids readability.

**Comment by seagreen** [comment]
I've now ended up in the same boat as @mietek. Would you like a PR to add the option for compact JSON?

**Comment by informatikr** [comment]
Version 0.8.0 on hackage has an option to remove all whitespace from the output (use `Spaces 0`). I suppose that covers your minification needs. If you need control over anything else, please open a new issue or PR.

There is now also an option for custom number formatting that might help any canonicalization efforts.

Thanks for your input and suggestions on the issue.
